# Generated by Django 5.0.6 on 2024-08-29 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(choices=[('Mumbai', 'Mumbai'), ('Bengaluru', 'Bengaluru'), ('Delhi', 'Delhi'), ('Kerala', 'Kerala')], max_length=100),
        ),
    ]
