# Generated by Django 5.0.6 on 2024-08-31 01:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_company_company_type'),
        ('jobapp', '0002_alter_job_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authapp.employee'),
        ),
    ]
