# Generated by Django 5.0.6 on 2024-08-31 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0004_jobapplication_employee_profile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='employee_profile',
        ),
    ]
