# Generated by Django 5.0.6 on 2024-09-01 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0005_remove_jobapplication_employee_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_category',
            field=models.CharField(blank=True, choices=[('Automotive Jobs', 'Automotive Jobs'), ('Health and Care', 'Health and Care'), ('Customer Service', 'Customer Service'), ('Project Management', 'Project Management'), ('Development', 'Development'), ('Design', 'Design'), ('Marketing', 'Marketing'), ('Accounting / Finance', 'Accounting / Finance')], max_length=100, null=True),
        ),
    ]
