# Generated by Django 5.0.6 on 2024-09-01 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0007_alter_job_job_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_category',
            field=models.CharField(blank=True, choices=[('Automotive-Jobs', 'Automotive-Jobs'), ('HealthCare', 'HealthCare'), ('Customer-Service', 'Customer-Service'), ('Project-Management', 'Project-Management'), ('Development', 'Development'), ('Design', 'Design'), ('Marketing', 'Marketing'), ('Accounting-Finance', 'Accounting-Finance')], max_length=100, null=True),
        ),
    ]
