# Generated by Django 5.0.6 on 2024-08-28 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='industry',
            field=models.CharField(choices=[('IT & Services', 'IT & Services'), ('Trading', 'Trading'), ('Food production', 'Food production'), ('Airlines', 'Airlines'), ('Entertainment', 'Entertainment'), ('Engineering & Construction', 'Engineering & Construction'), ('Other', 'Other')], max_length=100),
        ),
    ]
