# Generated by Django 5.0.6 on 2024-08-28 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_alter_company_industry'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_type',
            field=models.CharField(blank=True, choices=[('Corporate', 'Corporate'), ('Foreign MNC', 'Foreign MNC'), ('Indian MNC', 'Indian MNC'), ('Startup', 'Startup'), ('Others', 'Others')], max_length=100, null=True),
        ),
    ]
