# Generated by Django 5.0.6 on 2024-09-03 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_company_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='country',
        ),
    ]
