# Generated by Django 5.0.6 on 2024-09-03 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_company_company_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='location',
            field=models.CharField(blank=True, choices=[('Mumbai', 'Mumbai'), ('Bengaluru', 'Bengaluru'), ('Delhi', 'Delhi'), ('Kerala', 'Kerala')], max_length=100, null=True),
        ),
    ]
