# Generated by Django 5.0.6 on 2024-09-05 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0006_remove_company_city_remove_company_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='pin_code',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
    ]
